<h1>Hello</h1>
<?php if (!empty($flash)) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<?php if ($currentUser): ?>
    <a href="/users/new">Create user</a>
    <a href="/users">All users</a>
<div><?= $currentUser['name'] ?></div>
<form action="/session" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Sign Out">
</form>
<?php else: ?>
<form action="/session" method="post">
    <input type="text" required name="user[name]" value="">
    <input type="password" required name="user[password]" value="">
    <input type="submit" value="Sign In">
</form>
<?php endif; ?>
