<a href="/">hello</a>
<a href="/users/new">create users</a>

<form action="/users" method="GET">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<?php foreach ($users as $user): ?>
    <div>
        <a href="/users/<?= $user['id']?>"><?=htmlspecialchars($user['name']) ?></a>
    </div>
<?php endforeach; ?>

<?php if (!empty($flash)) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>