<form action="/users" method="post">
    <div>
        <label>name
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
        <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>password
            <input type="password" required name="user[password]" value="<?= htmlspecialchars($user['password'] ?? '') ?>">
        </label>
        <?php if (isset($errors['password'])): ?>
            <div><?= $errors['password'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>confirm password
            <input type="password" required name="user[passwordConfirmation]" value="<?= htmlspecialchars($user['passwordConfirmation'] ?? '') ?>">
        </label>
        <?php if (isset($errors['passwordConfirmation'])): ?>
            <div><?= $errors['passwordConfirmation'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Sign up">
</form>
