<?php foreach ($user as $key => $value): ?>
    <table>
        <tr><td><?= $key ?> :</td><td><?= $value ?></td></tr>
    </table>
<?php endforeach; ?>
<div>
    <form action="/users/<?= $user['id'] ?>/edit" method="get">
        <input type="submit" value="Edit">
    </form>
    <form action="/users/<?= $user['id'] ?>" method="post">
        <input type="hidden" name = "_METHOD" value="DELETE">
        <input type="submit" value="Delete">
    </form>
</div>
